export enum Events {
  START_GAME = 'START_GAME',
  GAME_STARTED = 'GAME_STARTED',
  PLAYER_CONNECTED = 'PLAYER_CONNECTED',
  LEAVE_GAME = 'LEAVE_GAME',
  CANCEL_GAME = 'CANCEL_GAME',
  JOIN_GAME = 'JOIN_GAME',
  CONNECT_PLAYER = 'CONNECT_PLAYER',
  MESSAGE = 'MESSAGE',
  UPDATE_PLAYERS = 'UPDATE_PLAYERS',
  CREATE_GAME = 'CREATE_GAME',
  UPDATE_GAMES = 'UPDATE_GAMES'
}
