enum GamePhase {
    WESTEROS1,
    WESTEROS2,
    WESTEROS3,
    PLANNING,
    ACTION_RAID,
    ACTION_MARCH,
    ACTION_CONSOLIDATE_POWER,
    ACTION_CLEANUP
}

let ACTION_PHASES = new Array(GamePhase.ACTION_RAID,
    GamePhase.ACTION_MARCH,
    GamePhase.ACTION_CONSOLIDATE_POWER,
    GamePhase.ACTION_CLEANUP);


let WESTEROS_PHASES = new Array(GamePhase.WESTEROS1,
    GamePhase.WESTEROS2,
    GamePhase.WESTEROS3);

export {WESTEROS_PHASES, ACTION_PHASES, GamePhase};